### ISSUE TITLE
Add more attributes to hdf5 measurement/configuration files

### ISSUE THREAD

**Issue by AlexVaq** [veintemillas/jaxions#34]
We should define each measurement file/configuration so there is complete information on how it was obtained

**Comment by veintemillas** [comment]
Here is a list!
MASS: indi3, zthreshold, zrestore, 
IC      : mode0, kmax, Kcrit
         : if smooth, then sIter ....
V       : VqcdType, shift, gammo
red    : reduced N, reducedDepth
+       : last_dz, lowmem, PropType

**Comment by AlexVaq** [comment]
Commit 302896c0240cae8fc9db8504d44d8fbef3b9d8bf solves the issue for parallel compression, I'll work on the normal version tomorrow.

I would discourage the storage of interdependent attributes, like indi3 and axion mass. We can have inconsistencies when reading the files from disk, and we'll be forced to choose a value. In the current implementation, some values are "canonical" and from those, the rest are deduced, even though these values are stored on disk.

**Comment by AlexVaq** [comment]
Close with commit ab7594640be1d7bc8bbf09bacf5e9e0a4e26e4bf

We have to revise the number of steps (it might be wrong in some cases)
