### ISSUE TITLE
energy map at the final measurement in restart mode

### ISSUE THREAD

**Issue by ksaikawa** [veintemillas/jaxions#66]
energy map (huge m file) is printed when restart_flag is true even if I do not specify it in the measfile.dat. This might be caused by the readConf function that assigns redmap = sizeN > 0 when it reads .restart file.

**Comment by veintemillas** [comment]
Solved by commit https://github.com/veintemillas/jaxions/commit/ba713434f9a40f4f1afabb59250579f2efffb0fa
